#!/usr/bin/env bash
set -euo pipefail
# Real database dump/restore and installed-runtime attestation, using tiny metadata only.
image="${1:-flat-white:ci}"
docker run --rm -i --network none --entrypoint bash "$image" -euo pipefail -s <<'CONTAINER'
provenance_db=$(mktemp -d /tmp/source-provenance.XXXXXX)
chown postgres:postgres "$provenance_db"
su postgres -c "initdb --auth=trust --encoding=UTF8 -D '$provenance_db'" >/dev/null
trap 'su postgres -c "pg_ctl -D '\''$provenance_db'\'' stop -m fast" >/dev/null || true' EXIT
su postgres -c "pg_ctl -D '$provenance_db' -l '$provenance_db/postgres.log' -o '-k /tmp -h 127.0.0.1' start -w" >/dev/null
export PGHOST=127.0.0.1 PGUSER=postgres PGDATABASE=postgres
psql -v ON_ERROR_STOP=1 -qc 'CREATE SCHEMA gnaf_202608'
node --input-type=module <<'NODE'
import {writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {databaseSourceProvenance} from '/app/dist/source-lock.js';
const lock = {
  formatVersion:1, gnafVersion:'2026.08', adminVersion:'2026.08', boundaryReferenceDate:'2026-08-31',
  acquiredAt:'2026-09-30T00:00:00.000Z', acquiredWith:{loaderCommit:'a'.repeat(40),preparationFingerprint:'b'.repeat(64),node:process.version},
  sources:['gnaf','admin'].map(kind=>({kind,name:kind,url:'https://fixture.invalid/'+kind+'.zip',resourceId:null,edition:'2026.08',archive:kind+'.zip',bytes:1,sha256:'c'.repeat(64),extractedDir:kind,sentinelPaths:['fixture'],inventory:[{path:'fixture',bytes:1,crc32:1}]})),
};
await writeFile('/tmp/source-lock.json',JSON.stringify(lock));
const options={lockPath:'/tmp/source-lock.json',connectionString:'postgres://postgres@127.0.0.1/postgres',states:['OT']};
await databaseSourceProvenance({...options,create:true});
await databaseSourceProvenance(options);
await assert.rejects(databaseSourceProvenance({...options,states:['ACT']}),/does not match/);
const changed=structuredClone(lock); changed.sources[0].sha256='d'.repeat(64);
await writeFile('/tmp/changed-lock.json',JSON.stringify(changed));
await assert.rejects(databaseSourceProvenance({...options,lockPath:'/tmp/changed-lock.json'}),/does not match/);
console.log('PASS: real database source/state attestation');
NODE
pg_dump -Fc > /tmp/base.dump
expect_rejection() {
  if "$@" >/tmp/rejection.log 2>&1; then
    echo 'ERROR: expected rejection'; exit 1
  fi
}
attestation=(python3 /app/scripts/cache_attestation.py)
common=(--lock /tmp/source-lock.json --dump /tmp/base.dump --states OT)
expect_rejection "${attestation[@]}" verify "${common[@]}"
"${attestation[@]}" create "${common[@]}"
"${attestation[@]}" verify "${common[@]}"
mkdir -p /app/scripts/__pycache__ /app/gnaf-loader/__pycache__
printf 'generated bytecode' > /app/scripts/__pycache__/generated.pyc
printf 'generated bytecode' > /app/gnaf-loader/__pycache__/generated.pyc
"${attestation[@]}" verify "${common[@]}"
expect_rejection "${attestation[@]}" verify --lock /tmp/changed-lock.json --dump /tmp/base.dump --states OT
expect_rejection "${attestation[@]}" verify --lock /tmp/source-lock.json --dump /tmp/base.dump --states ACT
cp /app/dist/load.js /tmp/load-original
printf '\n// changed preparation\n' >> /app/dist/load.js
expect_rejection "${attestation[@]}" verify "${common[@]}"
cp /tmp/load-original /app/dist/load.js
cp /tmp/base.dump /tmp/base-original
printf 'corruption' >> /tmp/base.dump
expect_rejection "${attestation[@]}" verify "${common[@]}"
cp /tmp/base-original /tmp/base.dump
"${attestation[@]}" verify "${common[@]}"
psql -v ON_ERROR_STOP=1 -qc 'DROP SCHEMA gnaf_202608 CASCADE'
pg_restore --exit-on-error -d postgres /tmp/base.dump
SOURCE_LOCK_PATH=/tmp/source-lock.json DATABASE_URL=postgres://postgres@127.0.0.1/postgres STATES=OT node /app/dist/source-lock.js verify-db
printf 'PASS: old, changed-source, changed-state, changed-runtime and corrupt dumps rejected; valid dump survives restore\n'
CONTAINER
