/**
 * generate-main-sql.ts — Generate address_full_main.sql from address_full.sql.
 *
 * Single source of truth: address_full.sql is the canonical flatten query.
 * This script extracts the SELECT body and rewrites CTE references to use
 * the pre-materialized temp tables created by address_full_prep.sql.
 *
 * Prevents drift between the legacy (CTE) and production (materialize) paths
 * that caused the v2026.04 streetType regression.
 *
 * Usage: npm run generate:sql          # regenerate
 *        npm run generate:sql -- --check  # CI check (exits non-zero if stale)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SQL_DIR = resolve(__dirname, "..", "sql");
const SOURCE_PATH = resolve(SQL_DIR, "address_full.sql");
const OUTPUT_PATH = resolve(SQL_DIR, "address_full_main.sql");

/** CTE names in address_full.sql → temp table names in address_full_prep.sql */
const CTE_TO_TEMP: Record<string, string> = {
  address_geocodes: "tmp_address_geocodes",
  locality_neighbours: "tmp_locality_neighbours",
  locality_alias_agg: "tmp_locality_alias_agg",
  street_alias_agg: "tmp_street_alias_agg",
  address_alias_agg: "tmp_address_alias_agg",
  address_secondary_agg: "tmp_address_secondary_agg",
};

/**
 * Table name substitutions for production vs fixture paths.
 * Fixture seeds create abs_2021_mb_lookup; gnaf-loader creates abs_2021_mb.
 * The prep SQL ensures abs_2021_mb exists (CREATE TABLE IF NOT EXISTS).
 */
const TABLE_SUBSTITUTIONS: Record<string, string> = {
  abs_2021_mb_lookup: "abs_2021_mb",
};

const GENERATED_HEADER = `-- address_full_main.sql — AUTO-GENERATED from address_full.sql
-- DO NOT EDIT THIS FILE DIRECTLY. Edit address_full.sql and run:
--   npm run generate:sql
--
-- Main flatten SELECT using pre-materialized temp tables.
-- Run address_full_prep.sql first to create the temp tables.
-- This query is a simple multi-join — efficient for cursor-based streaming at scale.
--
-- Usage: Called from src/flatten.ts via cursor-based streaming.
-- Schema: gnaf___SCHEMA_VERSION__, raw_gnaf___SCHEMA_VERSION__, admin_bdys___SCHEMA_VERSION__

`;

function extractSelectBody(sql: string): string {
  // The main SELECT starts at column 0 (no indentation).
  // All CTE SELECTs are indented inside their AS (...) blocks.
  const lines = sql.split("\n");
  let selectStartLine = -1;

  for (let i = 0; i < lines.length; i++) {
    // Match SELECT at column 0 (not indented, not inside a CTE)
    if (/^SELECT\b/.test(lines[i])) {
      selectStartLine = i;
      break;
    }
  }

  if (selectStartLine === -1) {
    throw new Error("Could not find the main SELECT statement (must start at column 0)");
  }

  return lines.slice(selectStartLine).join("\n");
}

function rewriteReferences(sql: string): string {
  let result = sql;

  // Replace CTE references with temp table names — only in table positions
  // (FROM/JOIN clauses), not in column aliases (AS ...).
  for (const [cteName, tempName] of Object.entries(CTE_TO_TEMP)) {
    // Match CTE name as a table reference: preceded by JOIN/FROM + whitespace, or
    // at line start. Avoid replacing "AS cteName" (column alias).
    // Strategy: replace all occurrences EXCEPT those preceded by "AS "
    const pattern = new RegExp(`(?<!AS )\\b${cteName}\\b`, "g");
    result = result.replace(pattern, tempName);
  }

  // Replace fixture-only table names with production equivalents.
  for (const [fixtureName, prodName] of Object.entries(TABLE_SUBSTITUTIONS)) {
    const pattern = new RegExp(`\\b${fixtureName}\\b`, "g");
    result = result.replace(pattern, prodName);
  }

  return result;
}

function generate(): string {
  const source = readFileSync(SOURCE_PATH, "utf-8");
  const selectBody = extractSelectBody(source);
  const rewritten = rewriteReferences(selectBody);
  return GENERATED_HEADER + rewritten;
}

function main() {
  const checkMode = process.argv.includes("--check");
  const generated = generate();

  if (checkMode) {
    let existing: string;
    try {
      existing = readFileSync(OUTPUT_PATH, "utf-8");
    } catch {
      console.error(
        "ERROR: sql/address_full_main.sql does not exist. Run: npx tsx scripts/generate-main-sql.ts",
      );
      process.exit(1);
    }
    if (existing !== generated) {
      console.error(
        "ERROR: sql/address_full_main.sql is out of date. Run: npx tsx scripts/generate-main-sql.ts",
      );
      process.exit(1);
    }
    console.log("OK: sql/address_full_main.sql is up to date");
    return;
  }

  writeFileSync(OUTPUT_PATH, generated, "utf-8");
  console.log("Generated sql/address_full_main.sql from sql/address_full.sql");
}

main();
